### PR TITLE
Make coding style more C++20 like

### PR DESCRIPTION
**Pull request by scc-tw**

### CODE REVIEW

**Comment by scc-tw** [comment]
We also could use concepts and constrains to replace std::enable_if<>.

Would you like to use that feature in C++20?

**Comment by jserv** [comment]
> We also could use concepts and constrains to replace std::enable_if<>.
> Would you like to use that feature in C++20?

Once it is successfully built with clang++-15, we can proceed to test the proposed changes.

**Comment by jserv** [comment]
Thank @25077667 for contributing!

**Comment by scc-tw** [comment]
> > We also could use concepts and constrains to replace std::enable_if<>.
> Once it is successfully built with clang++-15, we can proceed to test the proposed changes.

I found it's supported since clang++-10.
https://en.cppreference.com/w/cpp/20

**Pull request merged**
